# Generated by Django 3.1.1 on 2021-12-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=30)),
                ('expire', models.IntegerField(default=24)),
                ('last_change', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=60)),
            ],
        ),
    ]
