# Generated by Django 3.1.1 on 2021-12-07 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoodApp', '0002_auto_20211207_2249'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserData',
            new_name='Users',
        ),
    ]
