# Generated by Django 3.1.1 on 2021-12-07 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoodApp', '0003_auto_20211207_2251'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User_Data',
        ),
    ]
