# Generated by Django 3.1.1 on 2021-12-07 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoodApp', '0004_auto_20211207_2253'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Data',
            new_name='Users',
        ),
    ]
