# Generated by Django 3.2.9 on 2022-02-11 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoodApp', '0005_auto_20211207_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='accuracy',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='users',
            name='expire',
            field=models.PositiveSmallIntegerField(default=24, validators=[django.core.validators.MaxValueValidator(720), django.core.validators.MinValueValidator(1)]),
        ),
    ]
