# Generated by Django 3.2.9 on 2022-02-11 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoodApp', '0006_auto_20220211_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='accuracy',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
