# Generated by Django 3.1.1 on 2022-02-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoodApp', '0010_users_geohashlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='geohash_length',
            field=models.IntegerField(default=6),
        ),
    ]
