# Generated by Django 3.2.9 on 2022-03-17 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoodApp', '0011_auto_20220223_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='last_change',
        ),
        migrations.AddField(
            model_name='users',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
