# Generated by Django 3.2.9 on 2022-03-17 17:27

from django.db import migrations, models
import neighborhoodApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoodApp', '0012_auto_20220317_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='expiration_time',
        ),
        # migrations.AddField(
        #     model_name='users',
        #     name='expire_at',
        #     field=models.DateTimeField(default=neighborhoodApp.models.expire_time),
        # ),
    ]
