# Generated by Django 3.2.9 on 2022-03-17 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoodApp', '0013_auto_20220317_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 17, 17, 58, 32, 692547)),
        ),
    ]
