# Generated by Django 3.2.9 on 2022-03-17 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoodApp', '0015_alter_users_expire_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='expire_at',
        ),
    ]
