# Generated by Django 3.2.9 on 2022-03-17 18:05

from django.db import migrations, models
import neighborhoodApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoodApp', '0016_remove_users_expire_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='expire_at',
            field=models.DateTimeField(default=neighborhoodApp.models.defaultExpireAt),
        ),
    ]
