# Generated by Django 3.2.9 on 2022-03-17 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoodApp', '0018_alter_users_expire_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 17, 18, 10, 32, 139289), null=True),
        ),
    ]
