# Generated by Django 3.2.9 on 2022-03-25 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoodApp', '0019_alter_users_expire_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='expire',
        ),
        migrations.RemoveField(
            model_name='users',
            name='geohash',
        ),
        migrations.RemoveField(
            model_name='users',
            name='geohash_length',
        ),
        migrations.RemoveField(
            model_name='users',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='users',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='users',
            name='neighberhood_layers',
        ),
        migrations.AlterField(
            model_name='users',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 25, 13, 25, 44, 517767), null=True),
        ),
    ]
