# Generated by Django 3.2.9 on 2022-03-25 19:15

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoodApp', '0020_auto_20220325_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='expire',
            field=models.PositiveSmallIntegerField(default=24, validators=[django.core.validators.MaxValueValidator(720), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='users',
            name='geohash',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='users',
            name='latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='longitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 25, 19, 15, 8, 975823), null=True),
        ),
    ]
