# Generated by Django 3.2.9 on 2022-04-01 16:33

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoodApp', '0021_auto_20220325_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 1, 16, 33, 35, 774264), null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='geohash',
            field=models.CharField(default=0, max_length=10, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
