# Generated by Django 3.2.9 on 2022-04-06 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoodApp', '0022_auto_20220401_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 6, 13, 3, 56, 452435), null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
