# Generated by Django 3.2.9 on 2022-05-09 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoodApp', '0023_auto_20220406_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 9, 15, 2, 16, 490380), null=True),
        ),
    ]
